version: '3.8'

services:
  php-apache:
    build: .
    container_name: php-apache
    ports:
      - "8081:80"
    volumes:
      - ../participacion-social:/var/www/html
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: psd
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
